### ISSUE TITLE
Build failing with demo and Astro 1.4.4

### ISSUE THREAD

**Issue by webprogrammingsolutions** [delucis/astro-netlify-cms#22] opened 2022-10-06 13:07 UTC
Trying to build with Astro 1.4.4 and failing:

` generating static routes 
 error   component is not defined
ReferenceError: component is not defined
    at `file:///Users/psmith/Sites/nw-3-deploy-testing/test/.astro/entry.mjs?time=1665061500569:1780:25``

line 1780:

`__astro_tag_component__(component, "@astrojs/react");`

package.json:

`{
  "name": "@example/blog",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "npm run dev",
    "build": "astro build",
    "preview": "astro preview"
  },
  "devDependencies": {
    "astro": "^1.4.4",
    "astro-netlify-cms": "^0.2.2"
  }
}
`

**Comment by delucis** [comment] 2022-10-22 13:43
Hi @webprogrammingsolutions! Thanks for the bug report. I’m not able to reproduce this using the starter example project: <https://github.com/delucis/astro-netlify-cms-starter>

Would you be able to share a copy of your failing project? I’m wondering if the `component is not defined` error is triggered by something else in the project.

**Comment by delucis** [comment] 2022-10-29 13:54
Hi again @webprogrammingsolutions! Going to close this for now in the absence of a reproduction. Please do share more details if you have them!

**Closed as not planned by delucis** 2022-10-29 13:54 UTC
Labels: needs reproduction
